name: Local O1 System Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  system-test:
    runs-on: ubuntu-latest
    env:
      SKIP_OLLAMA: true  # Set true if mocking or skipping Ollama integration

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run system tests
      run: |
        source venv/bin/activate
        python system_test.py

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: system-test-results
        path: system_test_results.json
